# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import detailservice_pb2 as detailservice__pb2


class DetailServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPerson = channel.unary_unary(
        '/DetailService/GetPerson',
        request_serializer=detailservice__pb2.Details.SerializeToString,
        response_deserializer=detailservice__pb2.Person.FromString,
        )
    self.SavePerson = channel.unary_unary(
        '/DetailService/SavePerson',
        request_serializer=detailservice__pb2.Person.SerializeToString,
        response_deserializer=detailservice__pb2.Details.FromString,
        )


class DetailServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPerson(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SavePerson(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DetailServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPerson': grpc.unary_unary_rpc_method_handler(
          servicer.GetPerson,
          request_deserializer=detailservice__pb2.Details.FromString,
          response_serializer=detailservice__pb2.Person.SerializeToString,
      ),
      'SavePerson': grpc.unary_unary_rpc_method_handler(
          servicer.SavePerson,
          request_deserializer=detailservice__pb2.Person.FromString,
          response_serializer=detailservice__pb2.Details.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DetailService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
